version: '3.8'

services:
  pdfproject:
    container_name: pdfproject
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always